mysql:
    build: ./mysql
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./app/migrations/v1_0_0__baseline.sql:/tmp/migration.sql
    ports:
        - 3307:3306
    env_file:
        - ./.mysql-env
app:
    build: ./app
    volumes:
        - "./app:/src/app"
    ports:
        - 8000:8080
    links:
        - mysql
    env_file:
        - ./.mysql-env
